# Generated by hand for TanPit baseline

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=64, unique=True)),
                ("password_hash", models.CharField(max_length=256)),
                ("role", models.CharField(default="worker", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Yard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("village", models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Pit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=40)),
                ("status", models.CharField(default="fill", max_length=20)),
                ("row", models.IntegerField(default=0)),
                ("col", models.IntegerField(default=0)),
                (
                    "yard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pits",
                        to="pits.yard",
                    ),
                ),
            ],
            options={"unique_together": {("yard", "code")}},
        ),
        migrations.CreateModel(
            name="LiquorSample",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
                ("ph", models.FloatField()),
                ("operator", models.CharField(blank=True, max_length=64)),
                (
                    "pit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="pits.pit",
                    ),
                ),
            ],
        ),
    ]
